Ful corrections of the review.
williamtovar/Yutube_FerandWill pull request #6
Opened 2019-09-26 17:56 UTC by williamtovar

We do all the correction of the web https://validator.w3.org/, and add a comment in the readme abaut the logo of the web clone.

2019-09-26 20:05 UTC, Forison reviewed
# pull request under review by Addo

2019-09-26 20:18 UTC, Forison requested changes
# Hi team,👋👋
👌 job but we still need to improve a few things before merging

 - You should fix the errors given to you by the[ validator ](https://validator.w3.org)when uploading the index file.🙂

- It has at least three embedded images on the rightmost part of the navbar that represent icons and/or an avatar 🙂

- It has a subscribe button
> currently what you have there is an image.

- It’s better to delete commented code check line 23,51,52,102 of ```index.html```

**[optional]**
We highly recommend the usage of semantic HTML for each project. In fact, it is actually a requirement in some of your subsequent projects. I suggest you use it in the next.


### Kindly make those changes and submit for review

You are almost there Guys,
Happy coding

2019-09-28 01:16 UTC, bolah2009 requested changes
# Awesome job Team :smile: 

## [The clone](https://raw.githack.com/williamtovar/Yutube_FerandWill/cd8b98a791de62eaba7ab5f823a8480e1bae7fd2/index.html) looks good to me using HTML image effectively.

However, let's check the following:
- [REQUIRED] There should be an embedded video in the clone
- [REQUIRED] Use descriptive readme (Let's move comments about reviews to this PR (Pull Request) comments)
- Resolve merge conflicts
- Please try and use one PR throughout your review process, it makes it for TSEs  to follow-up with previous reviews easily

#### :recycle: Changes required

Good luck with your next submission. :star2: 

Cheers
[Bola](https://bolabuari.com/)

2019-09-28 01:16 UTC, bolah2009 commented on README.md
> +Sadly, we were right in our assumption that is was the best to create our own logo and images, since we contacted youtube (mexico) and were denied authorization to use their branding an immage, pleas
#### `HINT`

Add a descriptive readme. Details like assignment link (from Odin), live link (e.g. from [githack](https://raw.githack.com/)), screenshot and what was learned during the project can make the project more descriptive.

2019-09-28 01:16 UTC, bolah2009 commented on index.html
> +              </video>
Please let's embed an actual video. Remember the main objective of this project is embedding images and video.

2019-10-03 17:50 UTC, merged

2019-10-04 17:19 UTC, uche-inyama reviewed
## Hi team, good job

Kindly update your README as my colleague suggested, go through this [link](https://github.com/othneildrew/Best-README-Template), use it as a reference/guide; implement what fits your project requirement or what you have done in this project. :slightly_smiling_face: 

## After implementing the change, submit another form for a code review.

#### ``` Have a great day``` :slightly_smiling_face:

2019-10-08 21:06 UTC, stratospherique reviewed
### @williamtovar :wave: 

- Since you have merged this pull request and still have yet to apply reviewers suggestion about the README.md file. I suggest that you open a new pull request, make the changes and ask for code review again :pray: .

##### Happy coding :smiley_cat: